AWSTemplateFormatVersion: 2010-09-09
Description: Elastic Container Registory Repository to store ML containers

Resources:
  EcrRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: monsai-ml
Outputs:
  RepositoryUri:
    Description: The URI for the specified !Sub ${!Ref EcrRepo} repository. For example, 123456789012.dkr.ecr.us-west-2.amazonaws.com/repository.
    Value: !GetAtt EcrRepo.RepositoryUri
    Export:
      Name: !Sub '${AWS::AccountId}:${AWS::Region}:${AWS::StackName}:RepositoryUri'
