---
AWSTemplateFormatVersion: 2010-09-09
Description: IAM policies and roles for Sage Maker

Resources:
  DefaultReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SageMaker-DefaultReadOnly
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerReadOnly
      Tags:
        - Key: spa:owner
          Value: simone.spaccarotella@bbc.co.uk
        - Key: spa:project
          Value: sagemaker

  FullAccessRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SageMaker-FullAccess
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Tags:
        - Key: spa:owner
          Value: simone.spaccarotella@bbc.co.uk
        - Key: spa:project
          Value: sagemaker

  DataScientistRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SageMaker-DataScientist
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Ref SageMakerAndJumpStartS3BucketAccess
        - !Ref CommonJobManagement
        - !Ref ExperimentsManagement
        - !Ref ExperimentsVisualization
        - !Ref ModelManagement
        - !Ref StudioAppPermissions
        - !Ref TagPolicy
        - arn:aws:iam::aws:policy/AmazonSageMakerCanvasFullAccess
        - arn:aws:iam::aws:policy/AmazonSageMakerCanvasAIServicesAccess
        - arn:aws:iam::aws:policy/service-role/AmazonSageMakerCanvasForecastAccess
      Tags:
        - Key: spa:owner
          Value: simone.spaccarotella@bbc.co.uk
        - Key: spa:project
          Value: sagemaker

  MLOpsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: SageMaker-MLOps
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Ref EndpointDeployment
        - !Ref ExperimentsVisualization
        - !Ref ModelManagement
        - !Ref PipelineManagement
        - !Ref StudioAppPermissions
      Tags:
        - Key: spa:owner
          Value: simone.spaccarotella@bbc.co.uk
        - Key: spa:project
          Value: sagemaker

  EndpointDeployment:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SM_EndpointDeployment
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sagemaker:CreateEndpointConfig
              - sagemaker:CreateEndpoint
              - sagemaker:DeleteEndpointConfig
              - sagemaker:DeleteEndpoint
              - sagemaker:UpdateEndpoint
              - sagemaker:UpdateEndpointWeightsAndCapacities
              - sagemaker:DescribeEndpoint
              - sagemaker:DescribeEndpointConfig
            Resource: arn:aws:sagemaker:*:*:*/*
          - Effect: Allow
            Action:
              - sagemaker:ListEndpoints
              - sagemaker:ListEndpointConfigs
            Resource: '*'

  ExperimentsVisualization:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SM_ExperimentsVisualization
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sagemaker:DescribeAction
              - sagemaker:DescribeArtifact
              - sagemaker:DescribeContext
              - sagemaker:DescribeExperiment
              - sagemaker:DescribeTrial
              - sagemaker:DescribeTrialComponent
              - sagemaker:DescribeLineageGroup
            Resource: arn:aws:sagemaker:*:*:*/*
          - Effect: Allow
            Action:
              - sagemaker:ListAssociations
              - sagemaker:ListActions
              - sagemaker:ListArtifacts
              - sagemaker:ListContexts
              - sagemaker:ListExperiments
              - sagemaker:ListTrials
              - sagemaker:ListTrialComponents
              - sagemaker:ListLineageGroups
              - sagemaker:GetLineageGroupPolicy
              - sagemaker:QueryLineage
              - sagemaker:Search
              - sagemaker:GetSearchSuggestions
            Resource: '*'

  ModelManagement:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SM_ModelManagement
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sagemaker:CreateModel
              - sagemaker:CreateModelPackage
              - sagemaker:CreateModelPackageGroup
              - sagemaker:DescribeModel
              - sagemaker:DescribeModelPackage
              - sagemaker:DescribeModelPackageGroup
              - sagemaker:BatchDescribeModelPackage
              - sagemaker:UpdateModelPackage
              - sagemaker:DeleteModel
              - sagemaker:DeleteModelPackage
              - sagemaker:DeleteModelPackageGroup
            Resource: arn:aws:sagemaker:*:*:*/*
          - Effect: Allow
            Action:
              - sagemaker:ListModels
              - sagemaker:ListModelPackages
              - sagemaker:ListModelPackageGroups
            Resource: '*'
          - Effect: Allow
            Action: iam:PassRole
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/service-role/SageMaker-*'
            Condition:
              StringEquals:
                iam:PassedToService: sagemaker.amazonaws.com

  PipelineManagement:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SM_PipelineManagement
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sagemaker:CreatePipeline
              - sagemaker:StartPipelineExecution
              - sagemaker:StopPipelineExecution
              - sagemaker:RetryPipelineExecution
              - sagemaker:UpdatePipelineExecution
              - sagemaker:SendPipelineExecutionStepSuccess
              - sagemaker:SendPipelineExecutionStepFailure
              - sagemaker:DescribePipeline
              - sagemaker:DescribePipelineExecution
              - sagemaker:DescribePipelineDefinitionForExecution
              - sagemaker:DeletePipeline
            Resource: arn:aws:sagemaker:*:*:*/*
          - Effect: Allow
            Action:
              - sagemaker:ListPipelines
              - sagemaker:ListPipelineExecutions
              - sagemaker:ListPipelineExecutionSteps
              - sagemaker:ListPipelineParametersForExecution
            Resource: '*'
          - Effect: Allow
            Action: iam:PassRole
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/service-role/SageMaker-*'
            Condition:
              StringEquals:
                iam:PassedToService: sagemaker.amazonaws.com

  StudioAppPermissions:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SM_StudioAppPermissions
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: SMStudioAppPermissionsCRUD
            Effect: Allow
            Action:
              - sagemaker:CreateApp
              - sagemaker:CreateAppImageConfig
              - sagemaker:UpdateAppImageConfig
              - sagemaker:DeleteApp
              - sagemaker:DeleteAppImageConfig
              - sagemaker:DescribeApp
              - sagemaker:DescribeAppImageConfig
              - sagemaker:DescribeDomain
              - sagemaker:DescribeUserProfile
            Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*/*'
          - Sid: SMStudioAppPermissionsList
            Effect: Allow
            Action:
              - sagemaker:ListApps
              - sagemaker:ListAppImageConfigs
              - sagemaker:ListDomains
              - sagemaker:ListUserProfiles
            Resource: '*'
          - Sid: SMStudioAppPermissionsTagOnCreate
            Effect: Allow
            Action: sagemaker:AddTags
            Resource: !Sub 'arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:*/*'
            Condition:
              'Null':
                sagemaker:TaggingAction: false

  SageMakerAndJumpStartS3BucketAccess:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SM_SageMakerAndJumpStartS3BucketAccess
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: s3:ListBucket
            Resource:
              - !Sub 'arn:aws:s3:::sagemaker-${AWS::Region}-${AWS::AccountId}'
              - !Sub 'arn:aws:s3:::jumpstart-cache-prod-${AWS::Region}'
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: !Sub 'arn:aws:s3:::sagemaker-${AWS::Region}-${AWS::AccountId}/*'
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::jumpstart-cache-prod-${AWS::Region}/*'

  CommonJobManagement:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SM_CommonJobManagement
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sagemaker:CreateTrainingJob
              - sagemaker:CreateTransformJob
              - sagemaker:CreateProcessingJob
              - sagemaker:CreateAutoMLJob
              - sagemaker:CreateHyperParameterTuningJob
              - sagemaker:StopTrainingJob
              - sagemaker:StopProcessingJob
              - sagemaker:StopAutoMLJob
              - sagemaker:StopHyperParameterTuningJob
              - sagemaker:DescribeTrainingJob
              - sagemaker:DescribeTransformJob
              - sagemaker:DescribeProcessingJob
              - sagemaker:DescribeAutoMLJob
              - sagemaker:DescribeHyperParameterTuningJob
              - sagemaker:UpdateTrainingJob
              - sagemaker:BatchGetMetrics
            Resource: arn:aws:sagemaker:*:*:*/*
          - Effect: Allow
            Action:
              - sagemaker:Search
              - sagemaker:ListTrainingJobs
              - sagemaker:ListTransformJobs
              - sagemaker:ListProcessingJobs
              - sagemaker:ListAutoMLJobs
              - sagemaker:ListCandidatesForAutoMLJob
              - sagemaker:ListHyperParameterTuningJobs
              - sagemaker:ListTrainingJobsForHyperParameterTuningJob
            Resource: '*'
          - Effect: Allow
            Action: iam:PassRole
            Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/service-role/SageMaker-*'
            Condition:
              StringEquals:
                iam:PassedToService: sagemaker.amazonaws.com

  ExperimentsManagement:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SM_ExperimentsManagement
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sagemaker:AddAssociation
              - sagemaker:CreateAction
              - sagemaker:CreateArtifact
              - sagemaker:CreateContext
              - sagemaker:CreateExperiment
              - sagemaker:CreateTrial
              - sagemaker:CreateTrialComponent
              - sagemaker:UpdateAction
              - sagemaker:UpdateArtifact
              - sagemaker:UpdateContext
              - sagemaker:UpdateExperiment
              - sagemaker:UpdateTrial
              - sagemaker:UpdateTrialComponent
              - sagemaker:AssociateTrialComponent
              - sagemaker:DisassociateTrialComponent
              - sagemaker:DeleteAssociation
              - sagemaker:DeleteAction
              - sagemaker:DeleteArtifact
              - sagemaker:DeleteContext
              - sagemaker:DeleteExperiment
              - sagemaker:DeleteTrial
              - sagemaker:DeleteTrialComponent
            Resource: arn:aws:sagemaker:*:*:*/*

  TagPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: SM_TagPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sagemaker:AddTags
            Resource:
              - arn:aws:sagemaker:*:*:code-repository/*
              - arn:aws:sagemaker:*:*:endpoint/*
              - arn:aws:sagemaker:*:*:endpoint-config/*
              - arn:aws:sagemaker:*:*:image/*
              - arn:aws:sagemaker:*:*:model/*
              - arn:aws:sagemaker:*:*:workteam/*

Outputs:
  DefaultReadOnlyRoleArn:
    Description: The ARN of the DefaultReadOnly role
    Value: !GetAtt DefaultReadOnlyRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DefaultReadOnlyRoleArn'

  FullAccessRoleArn:
    Description: The ARN of the FullAccess role
    Value: !GetAtt FullAccessRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FullAccessRoleArn'

  DataScientistRoleArn:
    Description: The ARN of the DataScientist role
    Value: !GetAtt DataScientistRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-DataScientistRoleArn'

  MLOpsRoleArn:
    Description: The ARN of the MLOps role
    Value: !GetAtt MLOpsRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-MLOpsRoleArn'
